### ISSUE TITLE
rsrc merge failure: corrupt .rsrc section

### ISSUE THREAD

**Issue by pebble2050** [akavel/rsrc#26]
~~~~~~~
F:\care\work\gtool>go build
# _/F_/care/work/gtool
D:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: $WORK\b001\exe\a.out.exe: .rsrc merge failure: corrupt .rsrc section
F:\care\work\gtool>go env
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\jack\AppData\Local\go-build
set GOENV=C:\Users\jack\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\jack\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\msys64\mingw32\lib\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\msys64\mingw32\lib\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\jack\AppData\Local\Temp\go-build887004602=/tmp/go-build -gno-record-gcc-switches
~~~~~~~

**Comment by pebble2050** [comment]
I used cgo in my program.It's ok without cgo.
~~~~~~~~~~
package main

// int fortytwo()
// {
//      return 42;
// }
import "C"
import (
	"fmt"
	"os"

	"github.com/lxn/walk"
	"github.com/lxn/walk/declarative"
)

type toolMainWindow struct {
	*walk.MainWindow
}

// Start main
func main() {
	f := C.fortytwo()
	fmt.Println(int(f))

	var edit *walk.LineEdit // main
	mw := &toolMainWindow{}
	MW := declarative.MainWindow{
		AssignTo: &mw.MainWindow,
		Title:    "Tools Ver:2019100801",
		MinSize:  declarative.Size{Width: 150, Height: 200},
		Size:     declarative.Size{Width: 500, Height: 250},
		Layout:   declarative.VBox{},
		Children: []declarative.Widget{
			declarative.LineEdit{
				AssignTo: &edit,
			},
			declarative.PushButton{
				Text: "Test1",
				OnClicked: func() {
					path := edit.Text()
					if len(path) > 0 {
						walk.MsgBox(mw, "Test1", "Test1 Over",
							walk.MsgBoxIconError)
					} else {
						walk.MsgBox(mw, "Test1", "Test1 Over",
							walk.MsgBoxIconError)
					}
				},
			},
		},
	}

	if _, err := MW.Run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by akavel** [comment]
Hi @pebble2050, thank you very much for the report and for really good info! :heart:

Please note, I'm afraid that rsrc is now quite far down on my backburner list, so I'm not sure when I'll be able to get to this :(

That said, to hopefully help track this in future (fingers crossed), either by me or someone else, could you please also try to add the following small pieces of extra info: 

  1. the rsrc invocation you used to build your resources? (ideally, also the resources themselves, but even if not, it should be enough
  2. the command with which it works, vs. the command with which it does not (to clearly show the difference) &mdash; e.g. changing `CGO_ENABLED`, and which lines to comment out, etc.; or a git repo with 2 commits, one "before" and one "after"
 
TIA!

**Comment by pebble2050** [comment]
1.rsrc -manifest gtool.exe.manifest -o rsrc.syso
and here the manifest is

~~~~~~~~~~
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity version="1.0.0.0" processorArchitecture="*" name="SomeFunkyNameHere" type="win32"/>
  <dependency>
	<dependentAssembly>
	  <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/>
	</dependentAssembly>
  </dependency>
<application xmlns="urn:schemas-microsoft-com:asm.v3">
  <windowsSettings>
	<dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">True</dpiAware>
  </windowsSettings>
</application>
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
  <application>
	<!-- Windows Vista -->
	<supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
	<!-- Windows 7 -->
	<supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
	<!-- Windows 8 -->
	<supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
	<!-- Windows 8.1 -->
	<supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
	<!-- Windows 10 -->
	<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
  </application>
</compatibility>
</assembly>
~~~~~~~~~~~~~~~~~~~~~~

**Comment by pebble2050** [comment]
2.The source I paste above with below deleted is build and work fine.

~~~~~~~~~~~~~~~~~~~
// int fortytwo()
// {
//      return 42;
// }
import "C"
~~~~~~~~~~~~~~~~~~~~~
and 
~~~~~~~~~~~~~~
	f := C.fortytwo()
	fmt.Println(int(f))
~~~~~~~~~~~~~

**Comment by pebble2050** [comment]
3. The build dump

~~~~~~~~~~~~~~~
F:\care\work\gtool>go build -v -x
WORK=C:\Users\jack\AppData\Local\Temp\go-build814633394
golang.org/x/sys/windows
gopkg.in/Knetic/govaluate.v3
mkdir -p $WORK\b044\
mkdir -p $WORK\b051\
cat >$WORK\b051\importcfg << 'EOF' # internal
# import config
packagefile bytes=D:\msys64\mingw32\lib\go\pkg\windows_386\bytes.a
packagefile errors=D:\msys64\mingw32\lib\go\pkg\windows_386\errors.a
packagefile fmt=D:\msys64\mingw32\lib\go\pkg\windows_386\fmt.a
packagefile math=D:\msys64\mingw32\lib\go\pkg\windows_386\math.a
packagefile reflect=D:\msys64\mingw32\lib\go\pkg\windows_386\reflect.a
packagefile regexp=D:\msys64\mingw32\lib\go\pkg\windows_386\regexp.a
packagefile strconv=D:\msys64\mingw32\lib\go\pkg\windows_386\strconv.a
packagefile time=D:\msys64\mingw32\lib\go\pkg\windows_386\time.a
packagefile unicode=D:\msys64\mingw32\lib\go\pkg\windows_386\unicode.a
EOF
cat >$WORK\b044\importcfg << 'EOF' # internal
# import config
packagefile errors=D:\msys64\mingw32\lib\go\pkg\windows_386\errors.a
packagefile net=D:\msys64\mingw32\lib\go\pkg\windows_386\net.a
packagefile sync=D:\msys64\mingw32\lib\go\pkg\windows_386\sync.a
packagefile sync/atomic=D:\msys64\mingw32\lib\go\pkg\windows_386\sync\atomic.a
packagefile syscall=D:\msys64\mingw32\lib\go\pkg\windows_386\syscall.a
packagefile time=D:\msys64\mingw32\lib\go\pkg\windows_386\time.a
packagefile unicode/utf16=D:\msys64\mingw32\lib\go\pkg\windows_386\unicode\utf16.a
EOF
cd C:\Users\jack\go\src\golang.org\x\sys\windows
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\compile.exe" -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b044\\_pkg_.a" -trimpath "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b044=>" -p golang.org/x/sys/windows -complete -buildid yAUr8G_L_M2ZJ-yud9qz/yAUr8G_L_M2ZJ-yud9qz -goversion go1.13.4 -D "" -importcfg "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b044\\importcfg" -pack -c=4 "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\aliases.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\dll_windows.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\env_windows.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\eventlog.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\exec_windows.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\memory_windows.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\race0.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\security_windows.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\service.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\str.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\syscall.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\syscall_windows.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\types_windows.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\types_windows_386.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\zerrors_windows.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\zknownfolderids_windows.go" "C:\\Users\\jack\\go\\src\\golang.org\\x\\sys\\windows\\zsyscall_windows.go"
cd C:\Users\jack\go\src\gopkg.in\Knetic\govaluate.v3
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\compile.exe" -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b051\\_pkg_.a" -trimpath "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b051=>" -p gopkg.in/Knetic/govaluate.v3 -complete -buildid ZUsqu6rDedFkc7DVJH8Q/ZUsqu6rDedFkc7DVJH8Q -goversion go1.13.4 -D "" -importcfg "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b051\\importcfg" -pack -c=4 "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\EvaluableExpression.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\EvaluableExpression_sql.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\ExpressionToken.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\OperatorSymbol.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\TokenKind.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\evaluationStage.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\expressionFunctions.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\expressionOutputStream.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\lexerState.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\lexerStream.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\parameters.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\parsing.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\sanitizedParameters.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\stagePlanner.go" "C:\\Users\\jack\\go\\src\\gopkg.in\\Knetic\\govaluate.v3\\tokenStream.go"
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\buildid.exe" -w "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b051\\_pkg_.a" # internal
cp "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b051\\_pkg_.a" "C:\\Users\\jack\\AppData\\Local\\go-build\\9f\\9f2a2a2f154750f9613077b58eadfc055dce529871d356f8a0b8bb718fdb3a16-d" # internal
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\buildid.exe" -w "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b044\\_pkg_.a" # internal
cp "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b044\\_pkg_.a" "C:\\Users\\jack\\AppData\\Local\\go-build\\5e\\5eb57056677c001b72cef3432b6022955c7bbbf4e242dce71d0d0d01cebec3ea-d" # internal
github.com/lxn/win
mkdir -p $WORK\b043\
cat >$WORK\b043\importcfg << 'EOF' # internal
# import config
packagefile fmt=D:\msys64\mingw32\lib\go\pkg\windows_386\fmt.a
packagefile golang.org/x/sys/windows=$WORK\b044\_pkg_.a
packagefile syscall=D:\msys64\mingw32\lib\go\pkg\windows_386\syscall.a
EOF
cd C:\Users\jack\go\src\github.com\lxn\win
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\compile.exe" -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b043\\_pkg_.a" -trimpath "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b043=>" -p github.com/lxn/win -complete -buildid DZODhYWyz6hFY8IBpd6Y/DZODhYWyz6hFY8IBpd6Y -goversion go1.13.4 -D "" -importcfg "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b043\\importcfg" -pack -c=4 "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\advapi32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\combobox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\comctl32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\comdlg32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\datetimepicker.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\edit.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\gdi32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\gdiplus.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\header.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\kernel32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\listbox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\listview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\menu.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\ole32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\oleacc.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\oleacc_386.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\oleaut32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\oleaut32_386.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\opengl32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\pdh.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\shdocvw.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\shell32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\shobj.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\shobj_386.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\statusbar.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\syslink.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\tab.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\toolbar.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\tooltip.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\treeview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\updown.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\user32.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\uxtheme.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\win.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\win\\winspool.go"
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\buildid.exe" -w "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b043\\_pkg_.a" # internal
cp "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b043\\_pkg_.a" "C:\\Users\\jack\\AppData\\Local\\go-build\\11\\111a563bf9f9d7e9010d304c9206cced4912e854a07a45fee3c4074cfae8a5ad-d" # internal
github.com/lxn/walk
mkdir -p $WORK\b035\
cat >$WORK\b035\importcfg << 'EOF' # internal
# import config
packagefile bufio=D:\msys64\mingw32\lib\go\pkg\windows_386\bufio.a
packagefile bytes=D:\msys64\mingw32\lib\go\pkg\windows_386\bytes.a
packagefile encoding/json=D:\msys64\mingw32\lib\go\pkg\windows_386\encoding\json.a
packagefile errors=D:\msys64\mingw32\lib\go\pkg\windows_386\errors.a
packagefile fmt=D:\msys64\mingw32\lib\go\pkg\windows_386\fmt.a
packagefile github.com/lxn/win=$WORK\b043\_pkg_.a
packagefile golang.org/x/sys/windows=$WORK\b044\_pkg_.a
packagefile gopkg.in/Knetic/govaluate.v3=$WORK\b051\_pkg_.a
packagefile image=D:\msys64\mingw32\lib\go\pkg\windows_386\image.a
packagefile image/color=D:\msys64\mingw32\lib\go\pkg\windows_386\image\color.a
packagefile log=D:\msys64\mingw32\lib\go\pkg\windows_386\log.a
packagefile math=D:\msys64\mingw32\lib\go\pkg\windows_386\math.a
packagefile math/big=D:\msys64\mingw32\lib\go\pkg\windows_386\math\big.a
packagefile os=D:\msys64\mingw32\lib\go\pkg\windows_386\os.a
packagefile path/filepath=D:\msys64\mingw32\lib\go\pkg\windows_386\path\filepath.a
packagefile reflect=D:\msys64\mingw32\lib\go\pkg\windows_386\reflect.a
packagefile regexp=D:\msys64\mingw32\lib\go\pkg\windows_386\regexp.a
packagefile runtime=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime.a
packagefile runtime/debug=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime\debug.a
packagefile sort=D:\msys64\mingw32\lib\go\pkg\windows_386\sort.a
packagefile strconv=D:\msys64\mingw32\lib\go\pkg\windows_386\strconv.a
packagefile strings=D:\msys64\mingw32\lib\go\pkg\windows_386\strings.a
packagefile sync=D:\msys64\mingw32\lib\go\pkg\windows_386\sync.a
packagefile sync/atomic=D:\msys64\mingw32\lib\go\pkg\windows_386\sync\atomic.a
packagefile syscall=D:\msys64\mingw32\lib\go\pkg\windows_386\syscall.a
packagefile text/tabwriter=D:\msys64\mingw32\lib\go\pkg\windows_386\text\tabwriter.a
packagefile time=D:\msys64\mingw32\lib\go\pkg\windows_386\time.a
packagefile unicode/utf8=D:\msys64\mingw32\lib\go\pkg\windows_386\unicode\utf8.a
EOF
cd C:\Users\jack\go\src\github.com\lxn\walk
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\compile.exe" -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b035\\_pkg_.a" -trimpath "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b035=>" -p github.com/lxn/walk -complete -buildid FPa47vW75SQjamqDvbDk/FPa47vW75SQjamqDvbDk -goversion go1.13.4 -D "" -importcfg "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b035\\importcfg" -pack -c=4 "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\accessibility.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\action.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\actionlist.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\application.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\bitmap.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\boxlayout.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\brush.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\button.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\cancelevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\canvas.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\checkbox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\clipboard.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\closeevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\color.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\combobox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\commondialogs.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\composite.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\condition.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\container.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\cursor.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\customwidget.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\databinding.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\dateedit.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\datelabel.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\dialog.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\dropfilesevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\error.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\errorevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\event.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\expression.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\flowlayout.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\font.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\fontresource.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\form.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\gradientcomposite.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\graphicseffects.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\gridlayout.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\groupbox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\icon.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\iconcache.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\image.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\imagelist.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\imageview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\inifilesettings.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\intevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\intrangeevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\keyboard.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\keyevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\label.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\layout.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\lineedit.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\linklabel.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\listbox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\mainloop_default.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\mainwindow.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\maptablemodel.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\menu.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\messagebox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\metafile.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\models.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\mouseevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\notifyicon.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\numberedit.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\numberlabel.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\path.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\pen.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\point.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\progressbar.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\progressindicator.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\property.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\pushbutton.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\radiobutton.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\rectangle.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\reflectmodels.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\registry.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\resourcemanager.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\scrollview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\separator.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\simpletypes.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\size.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\slider.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\spacer.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\splitbutton.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\splitter.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\splitterhandle.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\splitterlayout.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\static.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\statusbar.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\stopwatch.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\stringevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\tableview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\tableviewcolumn.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\tableviewcolumnlist.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\tabpage.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\tabpagelist.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\tabwidget.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\textedit.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\textlabel.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\toolbar.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\toolbutton.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\tooltip.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\tooltiperrorpresenter.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\treeitemevent.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\treeview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\util.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\validators.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\walk.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\webview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\webview_dwebbrowserevents2.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\webview_events.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\webview_idochostuihandler.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\webview_ioleclientsite.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\webview_ioleinplaceframe.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\webview_ioleinplacesite.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\widget.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\widgetlist.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\window.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\windowgroup.go"
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\buildid.exe" -w "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b035\\_pkg_.a" # internal
cp "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b035\\_pkg_.a" "C:\\Users\\jack\\AppData\\Local\\go-build\\7c\\7cbf96a93f710fad4d28c73f17ebfc9af64576681003697a9113b3bd5c5483b4-d" # internal
github.com/lxn/walk/declarative
mkdir -p $WORK\b061\
cat >$WORK\b061\importcfg << 'EOF' # internal
# import config
packagefile bytes=D:\msys64\mingw32\lib\go\pkg\windows_386\bytes.a
packagefile errors=D:\msys64\mingw32\lib\go\pkg\windows_386\errors.a
packagefile fmt=D:\msys64\mingw32\lib\go\pkg\windows_386\fmt.a
packagefile github.com/lxn/walk=$WORK\b035\_pkg_.a
packagefile github.com/lxn/win=$WORK\b043\_pkg_.a
packagefile gopkg.in/Knetic/govaluate.v3=$WORK\b051\_pkg_.a
packagefile log=D:\msys64\mingw32\lib\go\pkg\windows_386\log.a
packagefile path/filepath=D:\msys64\mingw32\lib\go\pkg\windows_386\path\filepath.a
packagefile reflect=D:\msys64\mingw32\lib\go\pkg\windows_386\reflect.a
packagefile regexp=D:\msys64\mingw32\lib\go\pkg\windows_386\regexp.a
packagefile strconv=D:\msys64\mingw32\lib\go\pkg\windows_386\strconv.a
packagefile strings=D:\msys64\mingw32\lib\go\pkg\windows_386\strings.a
packagefile time=D:\msys64\mingw32\lib\go\pkg\windows_386\time.a
EOF
cd C:\Users\jack\go\src\github.com\lxn\walk\declarative
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\compile.exe" -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b061\\_pkg_.a" -trimpath "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b061=>" -p github.com/lxn/walk/declarative -complete -buildid DJ8Pl0qTw3SRo7OSGp__/DJ8Pl0qTw3SRo7OSGp__ -goversion go1.13.4 -D "" -importcfg "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b061\\importcfg" -pack -c=4 "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\accessibility.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\action.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\brush.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\builder.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\checkbox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\combobox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\composite.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\customwidget.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\databinder.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\dateedit.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\datelabel.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\dialog.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\font.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\gradientcomposite.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\groupbox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\imageview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\interfaces.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\label.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\layouts.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\lineedit.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\linklabel.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\listbox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\mainwindow.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\numberedit.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\numberlabel.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\progressbar.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\pushbutton.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\radiobutton.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\radiobuttongroup.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\radiobuttongroupbox.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\scrollview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\separator.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\slider.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\spacer.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\splitbutton.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\splitter.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\tableview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\tableviewcolumn.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\tabpage.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\tabwidget.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\textedit.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\textlabel.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\toolbar.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\toolbutton.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\treeview.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\validators.go" "C:\\Users\\jack\\go\\src\\github.com\\lxn\\walk\\declarative\\webview.go"
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\buildid.exe" -w "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b061\\_pkg_.a" # internal
cp "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b061\\_pkg_.a" "C:\\Users\\jack\\AppData\\Local\\go-build\\4b\\4b8e6ba97ec602769b7cf6c75320d77235bae519443968b6e700323e33b460ad-d" # internal
_/F_/care/work/gtool/garia2
mkdir -p $WORK\b002\
cd F:\care\work\gtool\garia2
CGO_LDFLAGS='"-g" "-O2"' "D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\cgo.exe" -objdir "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\" -importpath _/F_/care/work/gtool/garia2 -- -I "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\" -g -O2 "F:\\care\\work\\gtool\\garia2\\garia2.go"
cd $WORK
gcc -fno-caret-diagnostics -c -x c - -o NUL || true
gcc -Qunused-arguments -c -x c - -o NUL || true
gcc -fdebug-prefix-map=a=b -c -x c - -o NUL || true
gcc -gno-record-gcc-switches -c -x c - -o NUL || true
cd $WORK\b002
TERM='dumb' gcc -I "F:\\care\\work\\gtool\\garia2" -m32 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\" -g -O2 -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_x001.o" -c _cgo_export.c
TERM='dumb' gcc -I "F:\\care\\work\\gtool\\garia2" -m32 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\" -g -O2 -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_x002.o" -c garia2.cgo2.c
TERM='dumb' gcc -I "F:\\care\\work\\gtool\\garia2" -m32 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\" -g -O2 -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_cgo_main.o" -c _cgo_main.c
cd F:\care\work\gtool\garia2
TERM='dumb' gcc -I "F:\\care\\work\\gtool\\garia2" -m32 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002=/tmp/go-build" -gno-record-gcc-switches -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_cgo_.o" "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_cgo_main.o" "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_x001.o" "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_x002.o" -g -O2
TERM='dumb' "D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\cgo.exe" -dynpackage garia2 -dynimport "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_cgo_.o" -dynout "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_cgo_import.go"
cat >$WORK\b002\importcfg << 'EOF' # internal
# import config
packagefile fmt=D:\msys64\mingw32\lib\go\pkg\windows_386\fmt.a
packagefile github.com/lxn/walk=$WORK\b035\_pkg_.a
packagefile github.com/lxn/walk/declarative=$WORK\b061\_pkg_.a
packagefile os=D:\msys64\mingw32\lib\go\pkg\windows_386\os.a
packagefile runtime/cgo=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime\cgo.a
packagefile syscall=D:\msys64\mingw32\lib\go\pkg\windows_386\syscall.a
EOF
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\compile.exe" -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_pkg_.a" -trimpath "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002=>" -p _/F_/care/work/gtool/garia2 -buildid -_-4JxzXizZKHFl2IMgs/-_-4JxzXizZKHFl2IMgs -goversion go1.13.4 -D _/F_/care/work/gtool/garia2 -importcfg "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\importcfg" -pack -c=4 "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_cgo_gotypes.go" "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\garia2.cgo1.go" "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_cgo_import.go"
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\pack.exe" r "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_pkg_.a" "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_x001.o" "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_x002.o" # internal
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\buildid.exe" -w "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_pkg_.a" # internal
cp "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b002\\_pkg_.a" "C:\\Users\\jack\\AppData\\Local\\go-build\\94\\943f403a7e407f5672ae37871a4e971599b321d8daa1664b4cafb44f526ebf2e-d" # internal
_/F_/care/work/gtool
mkdir -p $WORK\b001\
cat >$WORK\b001\importcfg << 'EOF' # internal
# import config
importmap ./garia2=_/F_/care/work/gtool/garia2
packagefile _/F_/care/work/gtool/garia2=$WORK\b002\_pkg_.a
packagefile runtime=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime.a
EOF
cd F:\care\work\gtool
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\compile.exe" -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001\\_pkg_.a" -trimpath "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001=>" -p main -buildid 4z4GNSNE0meaSADQf_bU/4z4GNSNE0meaSADQf_bU -goversion go1.13.4 -D _/F_/care/work/gtool -importcfg "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001\\importcfg" -pack -c=4 "F:\\care\\work\\gtool\\main.go"
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\pack.exe" r "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001\\_pkg_.a" "F:\\care\\work\\gtool\\rsrc.syso" # internal
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\buildid.exe" -w "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001\\_pkg_.a" # internal
cp "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001\\_pkg_.a" "C:\\Users\\jack\\AppData\\Local\\go-build\\1b\\1b2728af31b2b221168fa2a861eab202450a153302e0f10649584a586924a2e9-d" # internal
cat >$WORK\b001\importcfg.link << 'EOF' # internal
packagefile _/F_/care/work/gtool=$WORK\b001\_pkg_.a
packagefile _/F_/care/work/gtool/garia2=$WORK\b002\_pkg_.a
packagefile runtime=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime.a
packagefile fmt=D:\msys64\mingw32\lib\go\pkg\windows_386\fmt.a
packagefile github.com/lxn/walk=$WORK\b035\_pkg_.a
packagefile github.com/lxn/walk/declarative=$WORK\b061\_pkg_.a
packagefile os=D:\msys64\mingw32\lib\go\pkg\windows_386\os.a
packagefile runtime/cgo=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime\cgo.a
packagefile syscall=D:\msys64\mingw32\lib\go\pkg\windows_386\syscall.a
packagefile internal/bytealg=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\bytealg.a
packagefile internal/cpu=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\cpu.a
packagefile runtime/internal/atomic=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime\internal\atomic.a
packagefile runtime/internal/math=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime\internal\math.a
packagefile runtime/internal/sys=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime\internal\sys.a
packagefile errors=D:\msys64\mingw32\lib\go\pkg\windows_386\errors.a
packagefile internal/fmtsort=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\fmtsort.a
packagefile io=D:\msys64\mingw32\lib\go\pkg\windows_386\io.a
packagefile math=D:\msys64\mingw32\lib\go\pkg\windows_386\math.a
packagefile reflect=D:\msys64\mingw32\lib\go\pkg\windows_386\reflect.a
packagefile strconv=D:\msys64\mingw32\lib\go\pkg\windows_386\strconv.a
packagefile sync=D:\msys64\mingw32\lib\go\pkg\windows_386\sync.a
packagefile unicode/utf8=D:\msys64\mingw32\lib\go\pkg\windows_386\unicode\utf8.a
packagefile bufio=D:\msys64\mingw32\lib\go\pkg\windows_386\bufio.a
packagefile bytes=D:\msys64\mingw32\lib\go\pkg\windows_386\bytes.a
packagefile encoding/json=D:\msys64\mingw32\lib\go\pkg\windows_386\encoding\json.a
packagefile github.com/lxn/win=$WORK\b043\_pkg_.a
packagefile golang.org/x/sys/windows=$WORK\b044\_pkg_.a
packagefile gopkg.in/Knetic/govaluate.v3=$WORK\b051\_pkg_.a
packagefile image=D:\msys64\mingw32\lib\go\pkg\windows_386\image.a
packagefile image/color=D:\msys64\mingw32\lib\go\pkg\windows_386\image\color.a
packagefile log=D:\msys64\mingw32\lib\go\pkg\windows_386\log.a
packagefile math/big=D:\msys64\mingw32\lib\go\pkg\windows_386\math\big.a
packagefile path/filepath=D:\msys64\mingw32\lib\go\pkg\windows_386\path\filepath.a
packagefile regexp=D:\msys64\mingw32\lib\go\pkg\windows_386\regexp.a
packagefile runtime/debug=D:\msys64\mingw32\lib\go\pkg\windows_386\runtime\debug.a
packagefile sort=D:\msys64\mingw32\lib\go\pkg\windows_386\sort.a
packagefile strings=D:\msys64\mingw32\lib\go\pkg\windows_386\strings.a
packagefile sync/atomic=D:\msys64\mingw32\lib\go\pkg\windows_386\sync\atomic.a
packagefile text/tabwriter=D:\msys64\mingw32\lib\go\pkg\windows_386\text\tabwriter.a
packagefile time=D:\msys64\mingw32\lib\go\pkg\windows_386\time.a
packagefile internal/oserror=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\oserror.a
packagefile internal/poll=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\poll.a
packagefile internal/syscall/windows=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\syscall\windows.a
packagefile internal/testlog=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\testlog.a
packagefile unicode/utf16=D:\msys64\mingw32\lib\go\pkg\windows_386\unicode\utf16.a
packagefile internal/race=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\race.a
packagefile internal/syscall/windows/sysdll=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\syscall\windows\sysdll.a
packagefile internal/reflectlite=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\reflectlite.a
packagefile math/bits=D:\msys64\mingw32\lib\go\pkg\windows_386\math\bits.a
packagefile unicode=D:\msys64\mingw32\lib\go\pkg\windows_386\unicode.a
packagefile encoding=D:\msys64\mingw32\lib\go\pkg\windows_386\encoding.a
packagefile encoding/base64=D:\msys64\mingw32\lib\go\pkg\windows_386\encoding\base64.a
packagefile net=D:\msys64\mingw32\lib\go\pkg\windows_386\net.a
packagefile encoding/binary=D:\msys64\mingw32\lib\go\pkg\windows_386\encoding\binary.a
packagefile math/rand=D:\msys64\mingw32\lib\go\pkg\windows_386\math\rand.a
packagefile regexp/syntax=D:\msys64\mingw32\lib\go\pkg\windows_386\regexp\syntax.a
packagefile internal/syscall/windows/registry=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\syscall\windows\registry.a
packagefile context=D:\msys64\mingw32\lib\go\pkg\windows_386\context.a
packagefile vendor/golang.org/x/net/dns/dnsmessage=D:\msys64\mingw32\lib\go\pkg\windows_386\vendor\golang.org\x\net\dns\dnsmessage.a
packagefile internal/nettrace=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\nettrace.a
packagefile internal/singleflight=D:\msys64\mingw32\lib\go\pkg\windows_386\internal\singleflight.a
EOF
mkdir -p $WORK\b001\exe\
cd .
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\link.exe" -o "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001\\exe\\a.out.exe" -importcfg "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001\\importcfg.link" -buildmode=exe -buildid=zKxnLZ0i0RtBiZUgNujR/4z4GNSNE0meaSADQf_bU/B5ndg9mQ3brEXLakkbFc/zKxnLZ0i0RtBiZUgNujR -extld=gcc "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001\\_pkg_.a"
"D:\\msys64\\mingw32\\lib\\go\\pkg\\tool\\windows_386\\buildid.exe" -w "C:\\Users\\jack\\AppData\\Local\\Temp\\go-build814633394\\b001\\exe\\a.out.exe" # internal
# _/F_/care/work/gtool
D:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: $WORK\b001\exe\a.out.exe: .rsrc merge failure: corrupt .rsrc section
cp $WORK\b001\exe\a.out.exe gtool.exe
rm -r $WORK\b001\

F:\care\work\gtool>
~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by pebble2050** [comment]
4. go version

~~~~~~~~~~~
:\care\work\gtool>go version
go version go1.13.4 windows/386
~~~~~~~~~~~~~~~~~~~~~

**Comment by Jonatino** [comment]
@pebble2050 did you find any fix for this? I'm getting the same error.

**Comment by rodolfoag** [comment]
Don't know if it helps, but I started to get the same error after update GCC to tdm64-gcc-9.2.0.

I was able to build using an older version of gcc (tdm64-gcc-5.1.0-2) that I have on my PC. I had to use `go build` with `-a` flag on my first new build.

Not sure if it's a gcc or rsrc issue.

**Comment by jjjabc** [comment]
-ldflags="-linkmode internal"

**Comment by lieuweberg** [comment]
Internal linkmode isn't a solution when using third-party packages. I'm running into this same issue.

**Comment by akavel** [comment]
Might hopefully be fixed now (starting with rsrc v0.10.0), thanks to @tc-hib ; please comment if this still occurs to you with rsrc v0.10.0.

**Comment by linquize** [comment]
For me with `rsrc` v0.10.1 + `github.com/mattn/go-sqlite3`,
`go build -ldflags="-linkmode internal"` works

**Comment by lieuweberg** [comment]
Note that that will mean you need gcc installed wherever you're running your executable. If you're distributing the executable to others that may pose an issue.

**Comment by akavel** [comment]
@lieuweberg 

>  you need gcc installed wherever you're running your executable

Are you sure this is correct? Can you share some link confirming that? I'm very surprised by this statement and honestly find it hard to believe, so I'd be grateful if you could share some reference so that I could get convinced.

**Comment by lieuweberg** [comment]
I think that's what's being said here.
https://go.googlesource.com/go/+/go1.16/src/cmd/cgo/doc.go#999

**Comment by tc-hib** [comment]
@akavel Are you sure this is fixed? I tried this icon: https://github.com/syncthing/syncthing/blob/main/assets/logo.ico

```
go install github.com/akavel/rsrc@latest
rsrc -ico logo.ico
```
![image](https://user-images.githubusercontent.com/55949036/110236043-0262fa00-7f34-11eb-9c52-cf0302d95088.png)


This is what go-winres does for the same icon (it has a different ordering, unfortunately):
```
go install github.com/tc-hib/go-winres@latest
go-winres simply --icon logo.ico
```
![image](https://user-images.githubusercontent.com/55949036/110235882-f165b900-7f32-11eb-9e29-504868132a73.png)

**Comment by tc-hib** [comment]
It is much slower and produces a much bigger file too, compared to rsrc v0.9.0 and go-winres.

**Comment by akavel** [comment]
Nope, I'm most certainly not sure... 😕

**Comment by tc-hib** [comment]
Should be fixed very soon anyway, it turned out to be a small oversight. Don't worry too much :)

**Comment by akavel** [comment]
I published another release [0.10.2](https://github.com/akavel/rsrc/releases/tag/v0.10.2) with a fix attempt suggested by @tc-hib . I still don't expect to be debugging this personally unfortunately, but hopefully this or some other suggestion from another interested contributor will help eventually; I'm especially open to a PR with an automated test case reproducing this bug as part of CI (see .travis.yml file), so that we could easily know when this is successfully closed.

**Comment by mappu** [comment]
Hey, unfortunately I can still see this error on v0.10.2.

```
/usr/lib/gcc/x86_64-w64-mingw32/10/../../../../x86_64-w64-mingw32/bin/ld: $WORK\b001\exe\a.out.exe: .rsrc merge failure: corrupt .rsrc section
```

Using GNU toolchain from Cygwin:

```
$ x86_64-w64-mingw32-ld.exe --version
GNU ld (GNU Binutils) 2.34.50.20200227

$ x86_64-w64-mingw32-gcc.exe --version
x86_64-w64-mingw32-gcc (GCC) 10.2.0
```

**Comment by tc-hib** [comment]
> Hey, unfortunately I can still see this error on v0.10.2.

Hello,
Can you share your syso file?

**Comment by tc-hib** [comment]
@mappu Can you please provide a little more information ? Such as the files you embedded, or the resulting syso file. Thanks.

**Comment by akavel** [comment]
@mappu if you could provide the information that @tc-hib is asking about, this could be really helpful in trying to fix your issue! It's showing to be really elusive and difficult to debug, so any help is greatly appreciated - and @tc-hib is an awesome contributor who's proven to be really positively hell-bent at trying to resolve it!
